sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && ./MKLBatch.out DHFR |tee  ./MKL_batch/O2/DHFR/DHFR_mklbatch_0.txt
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && ./MKLBatch.out DHFR |tee  ./MKL_batch/O2/DHFR/DHFR_mklbatch_1.txt
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && ./MKLBatch.out DHFR |tee  ./MKL_batch/O2/DHFR/DHFR_mklbatch_2.txt
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && ./MKLBatch.out DHFR |tee  ./MKL_batch/O2/DHFR/DHFR_mklbatch_3.txt
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && ./MKLBatch.out DHFR |tee  ./MKL_batch/O2/DHFR/DHFR_mklbatch_4.txt
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && ./MKLBatch.out DHFR |tee  ./MKL_batch/O2/DHFR/DHFR_mklbatch_5.txt
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && ./MKLBatch.out DHFR |tee  ./MKL_batch/O2/DHFR/DHFR_mklbatch_6.txt
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && ./MKLBatch.out DHFR |tee  ./MKL_batch/O2/DHFR/DHFR_mklbatch_7.txt
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && ./MKLBatch.out DHFR |tee  ./MKL_batch/O2/DHFR/DHFR_mklbatch_8.txt
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && ./MKLBatch.out DHFR |tee  ./MKL_batch/O2/DHFR/DHFR_mklbatch_9.txt
