sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && ./MKLBatch.out D5 |tee  ./MKL_batch/O2/D5/D5_mklbatch_0.txt
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && ./MKLBatch.out D5 |tee  ./MKL_batch/O2/D5/D5_mklbatch_1.txt
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && ./MKLBatch.out D5 |tee  ./MKL_batch/O2/D5/D5_mklbatch_2.txt
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && ./MKLBatch.out D5 |tee  ./MKL_batch/O2/D5/D5_mklbatch_3.txt
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && ./MKLBatch.out D5 |tee  ./MKL_batch/O2/D5/D5_mklbatch_4.txt
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && ./MKLBatch.out D5 |tee  ./MKL_batch/O2/D5/D5_mklbatch_5.txt
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && ./MKLBatch.out D5 |tee  ./MKL_batch/O2/D5/D5_mklbatch_6.txt
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && ./MKLBatch.out D5 |tee  ./MKL_batch/O2/D5/D5_mklbatch_7.txt
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && ./MKLBatch.out D5 |tee  ./MKL_batch/O2/D5/D5_mklbatch_8.txt
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && ./MKLBatch.out D5 |tee  ./MKL_batch/O2/D5/D5_mklbatch_9.txt
